### ISSUE TITLE
代码很多地方是被注释过的，请问能给出完整的网络结构的代码吗

### ISSUE THREAD

**Issue by Jay217219** [Asunatan/LM-Net#1]

**Comment by Jay217219** [comment]
LM_NET.py里面

**Comment by Asunatan** [comment]
感谢您对我的工作感兴趣，但是我已经毕业了，之前上传的版本是后续的一些改进尝试，毕业了就随便上传的，没想到真有人感兴趣，很水的工作，并且我最近查询到这个期刊已经on hold了，非常遗憾。之前的代码在学校服务器，估计已经进行了删除，但是我还是对代码进行了更新，同时我注意到NAT的算子进行了更新，和我22年用的版本有较大差距，我在Kvasir-SEG数据集上尝试重新复现，因为数据集是随机划分，可能和之前写文章的数据集有些差异，但基本能复现，下面是我的复现结果
![LM_NetV2](https://github.com/user-attachments/assets/ad3cfd20-14c2-4eb9-b3dd-91ced1a26f07)
希望对您有帮助！

**Comment by Jay217219** [comment]
感谢你的回复！








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Asunatan/LM-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月20日(星期三) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Asunatan/LM-Net] 代码很多地方是被注释过的，请问能给出完整的网络结构的代码吗 (Issue #1)





 
感谢您对我的工作感兴趣，但是我已经毕业了，之前上传的版本是后续的一些改进尝试，毕业了就随便上传的，没想到真有人感兴趣，很水的工作，并且我最近查询到这个期刊已经on hold了，非常遗憾。之前的代码在学校服务器，估计已经进行了删除，但是我还是对代码进行了更新，同时我注意到NAT的算子进行了更新，和我22年用的版本有较大差距，我在Kvasir-SEG数据集上尝试重新复现，因为数据集是随机划分，可能和之前写文章的数据集有些差异，但基本能复现，下面是我的复现结果
 LM_NetV2.png (view on web)
 希望对您有帮助！
